# Generated by Django 4.2.3 on 2023-07-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymskisdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='categories',
            new_name='category',
        ),
        migrations.AddField(
            model_name='gym',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gym',
            name='date_added',
            field=models.DateField(verbose_name='date_added'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='rating',
            field=models.FloatField(),
        ),
    ]
